name: common_github_app
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  stream_transform: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  lints: ^2.0.0
  test: ^1.16.0
